apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apic-client
  annotations:
    tekton.dev/tags: cli
    tekton.dev/displayName: "IBM API Connect client"
    tekton.dev/platforms: "linux/amd64"
spec:
  workspaces:
    - name: workspace
      description: workspace containing files to be used as input to apic commands
      readOnly: true
    - name: client-credentials
      description: ConfigMap containing client credentials json file identifying the target APIC installation.
      readOnly: true
    - name: basic-auth
      description: Secret containing username and password to login to the management server
      readOnly: true
  params:
    - name: APIC_CLIENT_IMAGE
      description: image containing apic client binaries
      type: string
    - name: SCRIPT
      description: The apic commands to run
      type: string
      default: "apic help"
    - name: MGMT_SERVER_URL
      description: URL to managment server api endpoint. Should end in /api. See https://www.ibm.com/docs/en/api-connect/10.0.x?topic=config-apic-configset
      type: string
    - name: PROVIDER_ORG
      type: string
    - name: CATALOG
      type: string
  steps:
    - name: apic-client
      image: $(params.APIC_CLIENT_IMAGE)
      script: |
        #!/usr/bin/env bash
         
        export USERNAME=$(cat $(workspaces.basic-auth.path)/username)
        export PASSWORD=$(cat $(workspaces.basic-auth.path)/password)
        
        set -x
      
        apic config:set cloud=$(params.MGMT_SERVER_URL)
        apic config:set org=$(params.MGMT_SERVER_URL)/orgs/$(params.PROVIDER_ORG)
        apic config:set catalog=$(params.MGMT_SERVER_URL)/catalogs/$(params.PROVIDER_ORG)/$(params.CATALOG)
        
        apic client-creds:clear
        apic client-creds:set $(workspaces.basic-auth.path)/client-credentials.json
        
        set +x 
        
        echo 'Logging in to $(params.MGMT_SERVER_URL)...'
        apic login --username $USERNAME --password $PASSWORD --realm provider/default-idp-2
            
        set -x
        
        $(params.SCRIPT)
