apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apic-client
  annotations:
    tekton.dev/tags: cli
    tekton.dev/displayName: "IBM API Connect client"
    tekton.dev/platforms: "linux/amd64"
spec:
  workspaces:
    - name: workspace
      optional: false
      description: workspace containing files to be used as input to apic commands
    - name: client-credentials
      optional: true
      description: ConfigMap containing client credentials json file identifying the target APIC installation
    - name: basic-auth
      optional: true
      description: Secret containing username and password to login to the management server
  params:
    - name: APIC_CLIENT_IMAGE
      description: image containing apic client binaries
      type: string
    - name: SCRIPT
      description: The apic commands to run
      type: string
      default: "apic help"
  steps:
    - name: apic-client
      image: $(params.APIC_CLIENT_IMAGE)
      script: |
        #!/usr/bin/env bash
        $(params.SCRIPT)
